clients/urls.py
from django.urls import path, re_path
from . import views
from .views import (
    client_list_view,
    session_list_view,
    client_delete_view,
    staff_list_view,
    staff_delete_view,
    delete_staff,
    staff_edit_view,
    client_edit_view,
    sessions_choices_ajax,
    BookingList,
    RoomListView,
    RoomDetailView,
    CancelBookingView,
    BookingAPIView,
    GenericAPIView,
    CalendarViewBooking   
)

#app_name= 'clients'

urlpatterns = [
    path('',views.client_list_view, name='home'),
    path('clients/<int:pk>/delete',
         client_delete_view.as_view(), name='client-delete'),
    path('sessions-list/', session_list_view, name='sessions-list'),
    path('sessions-list/sessions_choices_ajax/',
         sessions_choices_ajax,
         name='sessions_choices_ajax'),
    path('staff-list/', staff_list_view, name='staff-list'),
    path('staff-list/<int:id>/delete-staff',
         delete_staff, name='delete-staff'),
    path('staff-list/<int:id>/edit', staff_edit_view, name='staff-edit'),
    path('clients/<int:id>/edit', client_edit_view, name='client-edit'),



    ##Booking Stuff
    path('room_list/',RoomListView, name = 'RoomListView'),
    path('booking_list/',BookingList.as_view(), name = 'BookingList'),
    path('room/<category>', RoomDetailView.as_view(), name='RoomDetailView'),
    path('booking_list/api',BookingAPIView.as_view()),
    path('booking_list/api/<int:id>/',GenericAPIView.as_view()),
    path('booking/cancel/<pk>', CancelBookingView.as_view(), name='CancelBookingView'),
    path('booking_list/calendar/', CalendarViewBooking.as_view(), name = 'CalendarBooking'),
]

tootsie/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from tootsie import views as tootsie_views
from .views import ClientCreateView, SessionDeleteView

from .views import about_page
from django.conf.urls import url


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls'), name='accounts/login'),
    re_path(r'^about/$', about_page, name='about'),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(
        template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='templates/registration/logout.html'), name='logout'),
    path('sessions', views.sessions, name='sessions'),
    path('sessions-details', views.sessions_Details, name='sessions-details'),
    path('sessions-details-edit', views.sessions_Details_Edit,
         name='sessions-details-edit'),
    path('client-create', ClientCreateView.as_view(), name='client-create'),
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/(?P<event_id>\d+)/edit/$',
        views.event_edit, name='event_edit'),
    url(r'^event/(?P<event_id>\d+)/$',
        views.event_show, name='event_show'),
    url(r'^client/(?P<client_id>\d+)/$',
        views.client_show, name='client_show'),
    url(r'^client/(?P<client_id>\d+)/pay/sessions/$',
        views.client_show_pay_sessions, name='pay-sessions'),
    url(r'^staff/(?P<staff_id>\d+)/$',
        views.staff_show, name='staff_show'),
    path('event/<int:pk>/delete/',
         SessionDeleteView.as_view(), name='session-delete'),
    path('profile', views.profile, name='profile'),
    path('popUp', views.popUp, name='popUp'),
    path('profile/edit', views.profile_edit, name='profile-edit'),
    path('profile/edit/change-password',
         views.change_password, name='change-password'),
    url(r'^profile/password/$', views.change_password, name='change_password'),
    url(r'^register/$', views.register, name='register'),
    path('', include('clients.urls')),

    
] + staticfiles_urlpatterns()


if settings.DEBUG:
    # test mode
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

clients/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, timedelta, date
from django.urls import reverse, reverse_lazy
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_countries.fields import CountryField
from django.conf import settings 
# Create your models here.

GENDER_CHOICES = (
    ("male", "male"),
    ("female", "female"),
)


class Client(models.Model):
    name = models.CharField(max_length=255, blank=False)
    email = models.EmailField(max_length=254, blank=True)
    gender = models.CharField(choices=GENDER_CHOICES,
                              max_length=254, blank=True, default=GENDER_CHOICES[0])
    birthday = models.CharField(max_length=255, blank=True)
    country = models.CharField(max_length=255, blank=True, default="Portugal")
    phone = models.CharField(max_length=12, blank=False)
    nIF = models.CharField(max_length=9, blank=True, validators=[RegexValidator(
        regex='^.{9}$', message='Length has to be 9', code='nomatch')])
    balance = models.FloatField(blank=True, default=0.0)
    debt = models.IntegerField(blank=True, default=0)
    discount = models.IntegerField(blank=True, default=0)
    notes = models.TextField(default="", blank=True)

    def __str__(self):
        """ String para representar o objeto MyModelName (no site Admin)."""
        return self.name

    def get_absolute_url(self):
        return f"/clients/{self.id}/"


class Profile(models.Model):
    """ modelo do staff """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    firstName = models.CharField(max_length=30, blank=True, default="")
    lastName = models.CharField(max_length=30, blank=True, default="")
    phone = models.CharField(max_length=15, blank=True)
    address = models.CharField(max_length=30, blank=True, default="")
    birthday = models.DateField(null=True, blank=True)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    driver = models.BooleanField(blank=True, default=False)
    instructor = models.BooleanField(blank=True, default=False)

    def __str__(self):
        return f'{self.user.username}'

    def delete_user(self):
        self.user.delete()

    def get_driver(self):
        if self.driver == True:
            return "yes"
        elif self.driver == False:
            return "no"
        else:
            return "None"

    def get_instructor(self):
        if self.instructor == True:
            return "yes"
        elif self.instructor == False:
            return "no"
        else:
            return "None"

    def get_absolute_url(self):
        return f"/profile/edit/{self.id}/"


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


class Gender(models.Model):
    name = models.CharField(max_length=255, blank=False)

    def __str__(self):
        """ String para representar o objeto MyModelName (no site Admin)."""
        return self.name


class Driver(models.Model):
    name = models.CharField(max_length=255, blank=False)
    email = models.EmailField(max_length=254, blank=True)

    def __str__(self):
        """ String para representar o objeto MyModelName (no site Admin)."""
        return self.name


class Modalidade(models.Model):
    name = models.CharField(blank=True, max_length=32, null=False)
    price = models.FloatField(blank=True, null=True)

    def __str__(self):
        """ String para representar o objeto MyModelName (no site Admin)."""
        return self.name

    def getName(self):
        return self.name


class Boat(models.Model):
    name = models.CharField(blank=True, max_length=32, null=False)

    def __str__(self):
        """ String para representar o objeto MyModelName (no site Admin)."""
        return self.name


class Instructor(models.Model):
    name = models.CharField(max_length=255, blank=False)
    email = models.EmailField(max_length=254, blank=True)

    def __str__(self):
        """ String para representar o objeto MyModelName (no site Admin)."""
        return self.name


def get_clients():
    return Client.objects.all()


class Event(models.Model):
    client = models.ForeignKey(Client, null=False, blank=False, on_delete=models.CASCADE)
    start_time = models.DateTimeField(default=datetime.now())
    end_time = models.DateTimeField(default=datetime.now())
    time = models.IntegerField(default=0, blank=True)
    driver = models.ForeignKey(Profile, null=False, on_delete=models.CASCADE, blank=True, related_name='driverr')
    instructor = models.ForeignKey(Profile, null=False, on_delete=models.CASCADE, blank=True, related_name='instructorr')
    boat = models.ForeignKey(Boat, null=False, on_delete=models.CASCADE, blank=True)
    modality = models.ForeignKey(Modalidade, null=False, on_delete=models.CASCADE, default="")
    price = models.FloatField(blank=True, default=0)
    payed = models.BooleanField(default=False, blank=False)
    grades = models.TextField(blank=True, default="")


    def __str__(self):
        """ String para representar o objeto MyModelName (no site Admin)."""
        return self.client.name

    def getId(self):
        return self.id

    def get_absolute_url(self):
        return f"/event/{self.id}/edit/"

    def get_notes(self):
        if self.grades.__sizeof__ == 0:
            return "None"
        else:
            return self.grades

    def get_payed(self):
        if self.payed == True:
            return "yes"
        elif self.payed == False:
            return "no"

    def hour_auto(self):
        self.end_time = django.utils.timezone.now()
        return self

    @property
    def get_html_url(self):
        url = reverse('event_edit', args=(self.id,))    
        return f'<a href="{url}"> {self.client.name} {self.start_time} {self.end_time}a </a>'




##Booking stuff
class Room(models.Model):

    ROOM_CATEGORIES = ( 
        ('BLU','BLUE'),
        ('VER','GREEN'),
        ('AMA','YELLOW'),
        ('RED','RED'),
        ('SIL','SILVER'),
    
    )

    category = models.CharField(blank = True,max_length=3,choices=ROOM_CATEGORIES)
    descricao_quarto = models.CharField(blank= True, max_length= 32, null=False)
    num_camas = models.IntegerField()
    image = models.ImageField(default='logo.png', upload_to='static/')
    preco = models.IntegerField(default=60)
    def __str__(self):
        return f'{self.category}'
    
    @property
    def get_room_category(self):
        room_categories = dict(self.ROOM_CATEGORIES)
        room_category = room_categories.get(self.category)
        return room_category
    
    @property
    def get_room_color(self):
        if self.category == "VER":
            color = "#32CD32"
            return color 
        elif self.category == "BLU":
            color =  "#87CEFA"
            return color 
        elif self.category == "AMA":
            color =  "#CCCC00"
            return color 
        elif self.category == "RED":
            color =  "#FF0000"
            return color
        elif self.category == "SIL":
            color =  "#A9A9A9"
            return color

    
    @property
    def get_image(self):
        return self.image

class Epoca(models.Model):
    EPOCAS_CHOICES = (
        ("Alta","Alta"),
        ("Baixa","Baixa"),
    )
    epoca = models.CharField(max_length = 20, choices = EPOCAS_CHOICES, default = 'Alta')

    def __str__(self):
        return f'{self.epoca}'
        
        
class Booking(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    client = models.ForeignKey(Client,on_delete=models.CASCADE, null = True)
    room = models.ForeignKey(Room,on_delete=models.CASCADE)   
    check_in = models.DateTimeField()
    check_out = models.DateTimeField()
    preco_total = models.IntegerField(default=60)
    epoca = models.ForeignKey(Epoca, on_delete=models.CASCADE, null= True)
    premium = models.BooleanField(default=False, blank= True)

    

    def __str__(self):
        return f' {self.client} has booked {self.room} From {self.check_in.strftime("%d / %m / %Y  %H:%M ")}   To {self.check_out.strftime("%d / %m / %Y  %H:%M ")} epoca: {self.epoca} premium: {self.premium} TOTAL PRICE: {self.preco_total} €'

    def get_room_category(self):
        room_categories = dict(self.room.ROOM_CATEGORIES)
        room_category = room_categories.get(self.room.category)
        return room_category

    def cancel_booking_url(self):
        return reverse_lazy('CancelBookingView', args=[self.pk])

    @property 
    def get_html_url(self):
        url = reverse('CancelBookingView', args=(self.id,))
        return f'<div style="background-color:{self.room.get_room_color};border:1px solid black; margin-bottom: 5px"> <a style="color:black; margin-left: 5em" title = "Cancel Booking"href = "{url}">ID: {self.id} <br> {self.client.name} booked {self.room.get_room_category} {self.check_in.strftime("%H:%M")} <p> {self.preco_total} €</p></a></div>'

clients/templates/clients/client_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Client</legend>
                <h2>Are you sure you want to delete the client "{{ object.name }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'home' %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

clients/templates/clients/client_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<div class="alert alert-danger">
    {{ field.label }} <strong>{{ error|escape }}</strong>
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger">
    {{ field.label }} <strong>{{ error|escape }}</strong>
</div>
{% endfor %}
{% endif %}

<form method="post">
    {% csrf_token %}
    <table class="form form-table">
    <h2 class="display-4 font-italic centered">New Client</h2>
    <legend class="border-bottom mb-4 centered"></legend>
        {{ form }}
        <tr>
            <td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td>
    </table>
</form>
{% endblock %}

clients/templates/clients/detail.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron text-white rounded bg-dark mt-4">
	<h1 class="display-4 font-italic">{{ client.name }}</h1>
	<div class="mb-1 text-muted">{{ client.email }}</div>
	<div class="mb-1 text-muted">Something</div>
	<div class="mb-1 text-muted">Something</div>
	<p class="lead my-3">Something</p>
</div>

<table>
<tr>
<th> data</th>
<th> modalidade </th>
<th> duracao </th>
<th> preco </th>
</tr>
{% for o in sessions %}
{%if o.client.name == client.name %}
<tr>
<td>{{ o.date }}</td>
<td>{{ o.modality.name }}</td>
<td>{{ o.time }}</td>
<td>{{ o.price }}</td>
</tr>
{% endif %}
{% endfor %}
</table

<div class="row">
	<div class="col-md-12">
		<div class="card border rounded shadow-sm mb-4 mt-4">
			<div class="card-body text-center">
				<h5 class="car-title mb-2 text-primary">Clients</h5>
				<p class="card-text mb-auto">

					<table class="table">
						<thead>
							<tr>
							<th scope="col">modalidade</th>
							<th scope="col">Data</th>
						</tr>
						</thead>
						<tbody>
							{% for o in events %}
							<tr>
								<td>{{ o.modality.name }}</td>
								<td>{{ o.start_time }}</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</p>
			</div>
		</div>
	</div>
</div>

{% endblock %}

clients/templates/clients/edit.html
{% extends "base.html" %}


{% block content %}

<form method="post">
    {% csrf_token %}
    <table class="form form-table">
    <h2 class="display-4 font-italic centered">Client profile edit</h2>
    <legend class="border-bottom mb-4 centered"></legend>
        {{ form}}
        <tr>
            <td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td>
    </table>
</form>
{% endblock %}

clients/templates/clients/event_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Session</legend>
                <h2>Are you sure you want to delete the session "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'sessions-list' %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

clients/templates/clients/list.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}

<style>
	label {
		padding: 10px;
	}
</style>

<div class="jumbotron text-white rounded bg-grey mt-4">
	<h1 class="display-4 font-italic centered">List of Client's</h1>
	<div class="container">
		<div style="border: dashed 1px grey;">
			<form id="myForm"
				method="GET"
				class="form-inline"
				>

				<div class="form-group">
					<label  style="color: blue; font-weight: bold" for="clientID">Client ID</label>
					<input type="number" class="form-control" id="clientID" name="clientID" placeholder="Client ID">
				</div>
				
				<div class="form-group" style="padding:10px;">
					<label style="color: blue; font-weight: bold" for="SessionSelect">Client Order</label>
					{% render_field form.idOrder title="Client Order" class="form-control" %}
				</div>
				
				<div class="form-group" style="padding:10px;">
					<label style="color: blue; font-weight: bold" for="SessionSelect">Balance</label>
					{% render_field form.balance title="Balance" class="form-control" %}
				</div>

				<div class="form-group" style="padding:10px;">
					<label style="color: blue; font-weight: bold" for="SessionSelect">Debt</label>
					{% render_field form.debt title="Debt" class="form-control" %}
				</div>

				<div class="form-group" style="padding:10px;">
					<label style="color: blue; font-weight: bold" for="SessionSelect">Discount</label>
					{% render_field form.discount title="Discount" class="form-control" %}
				</div>
				
				<div class="form-group">
					<button class="btn btn-success" type="submit"> Filter</button>
				</div>
			</form>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="card border rounded shadow-sm mb-4 mt-4">
			<div class="card-body text-center">
				<h5 class="car-title mb-2" style="color: blue">Client's</h5>
				<p class="card-text mb-auto">

					<table class="table">
						<thead>
							<tr>
							<th scope="col">ID</th>
							<th scope="col">Name</th>
							<th scope="col">NIF</th>
							<th scope="col">Email</th>
							<th scope="col">Balance €</th>
							<th scope="col">Debt €</th>
							<th scope="col">Discount %</th>
							<!--
							<th scope="col">Edit</th>
							<th scope="col">Delete</th>
							-->
						</tr>
						</thead>
						<tbody>

							{% if clients%}
								{% for o in clients %}
							
								<tr>
									<td scope="row"><a href="{% url 'client_show' o.id %}">{{ o.id }}</a></td>
									<td>{{ o.name }}</td>
									<td>{{ o.nIF }}</td>
									<td>{{ o.email }}</td>
									<td>{{ o.balance }}</td>
									<td>{{ o.debt }}</td>
									<td>{{ o.discount }}</td>
									<!--  
									<td scope="row"><a href="{% url 'client-edit' o.id %}"><button class="btn btn-warning">Edit</button></a></td> 
									<td scope="row"><a href="{% url 'client-delete' o.id %}"><button class="btn btn-danger delete">Delete</button></a></td>
									-->
									
									
								</tr>
								
							{% endfor %}
							{% else %}
							<td> </td>
							<td> </td>
							<td> </td>
							<td class="centered"><h3><b><i><u>No registered customers</u></i></b></h3><td>
							<td> </td>
							{% endif %}
							
						</tbody>
					</table>
				</p>
			</div>
		</div>
	</div>
</div>


{% endblock content%}


{% block js %}

	<script>
		$('#id_idOrder').change(function() {
			let ufIdSession = $(this).val();
			console.log(ufIdSession);
		});
	</script>

	<script>
		$('#id_balance').change(function() {
			let ufIdSession = $(this).val();
			console.log(ufIdSession);
		});
	</script>

	<script>
		$('#id_debt').change(function() {
			let ufIdSession = $(this).val();
			console.log(ufIdSession);
		});
	</script>

	<script>
		$('#id_discount').change(function() {
			let ufIdSession = $(this).val();
			console.log(ufIdSession);
		});
	</script>


{% endblock js %}

clients/templates/clients/profile_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Staff</legend>
                <h2>Are you sure you want to delete the Staff "{{ object.user.username }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'staff-list' %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}